language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
  #- "3.7"
addons:
  apt:
    packages:
      - pandoc
      - texlive-base
      - libmagic-dev
install: "pip install -r requirements.txt"
script:
  - "make test"
after_success:
  - ./run-coveralls.sh
